import os, sys, django, datetime
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'smart_service.settings')
django.setup()
from core.models import CustomUser, Category, Service, ServiceProvider

print("Seeding SmartService v5...")

# ── CATEGORIES ────────────────────────────────
cats_data = [
    ('Doctor','fa-user-md','🏥','Medical consultations',1,False),
    ('Mechanic','fa-car','🚗','Vehicle repair',2,False),
    ('Tutor','fa-graduation-cap','🎓','Academic coaching',3,True),   # online_only=True
    ('Plumber','fa-faucet','🔧','Plumbing services',4,False),
    ('Electrician','fa-bolt','⚡','Electrical services',5,False),
    ('Cleaner','fa-broom','🧹','Cleaning services',6,False),
    ('Carpenter','fa-hammer','🪚','Woodwork services',7,False),
    ('Salon','fa-cut','✂️','Hair and beauty',8,False),
]
cats={}
for name,icon,emoji,desc,order,online_only in cats_data:
    obj,_=Category.objects.update_or_create(name=name,
        defaults={'icon':icon,'emoji':emoji,'description':desc,'order':order,'online_only':online_only})
    cats[name]=obj
    print(f"  Category: {emoji} {name}")

# ── SERVICE PROVIDERS ─────────────────────────
providers_raw = [
    # DOCTORS (22 providers - one per service)
    dict(cat='Doctor',full_name='Dr. Rajesh Kumar',phone='9876541001',uname='dr_rajesh',
         edu='MBBS, MD - Internal Medicine',spec='General Physician',exp=15,
         workplace='Apollo Hospital Bangalore',addr='154/11, Bannerghatta Road, Bangalore 560076',
         lat=12.8908,lng=77.5978,about='Senior physician with 15 years experience in general medicine and preventive healthcare.',
         emerg='+91 9876541001',langs='Kannada, Hindi, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Amit Sharma',phone='9876541002',uname='dr_amit',
         edu='MBBS, DM - Cardiology',spec='Cardiologist',exp=18,
         workplace='Fortis Hospital Bangalore',addr='154, Bannerghatta Road, Bangalore 560076',
         lat=12.8910,lng=77.5979,about='Interventional cardiologist specializing in heart disease management.',
         emerg='+91 9876541002',langs='Hindi, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Sunita Nair',phone='9876541003',uname='dr_sunita',
         edu='MBBS, DM - Neurology',spec='Neurologist',exp=12,
         workplace='Manipal Hospital Bangalore',addr='98 HAL Airport Road, Bangalore 560017',
         lat=12.9592,lng=77.6493,about='Expert in stroke, epilepsy and neurodegenerative diseases.',
         emerg='+91 9876541003',langs='Malayalam, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Vikram Singh',phone='9876541004',uname='dr_vikram',
         edu='MBBS, MS - Orthopaedics',spec='Orthopedic Doctor',exp=14,
         workplace='Columbia Asia Hospital',addr='26/4 Brigade Gateway, Bangalore 560055',
         lat=13.0067,lng=77.5553,about='Sports medicine and joint replacement specialist.',
         emerg='+91 9876541004',langs='Hindi, English, Kannada',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Rekha Pillai',phone='9876541005',uname='dr_rekha',
         edu='MBBS, MPT - Physiotherapy',spec='Physiotherapist',exp=8,
         workplace='Sparsh Hospital Bangalore',addr='29/P2, Infantry Road, Bangalore 560001',
         lat=12.9784,lng=77.5959,about='Certified physiotherapist for sports injuries and post-surgery recovery.',
         emerg='+91 9876541005',langs='Malayalam, Kannada, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Arun Nair',phone='9876541006',uname='dr_arun',
         edu='MBBS, DCH - Pediatrics',spec='Pediatrician',exp=10,
         workplace='Rainbow Childrens Hospital',addr='78, Bannerghatta Road, Bangalore 560029',
         lat=12.9116,lng=77.5945,about='Child health specialist for all age groups 0-18 years.',
         emerg='+91 9876541006',langs='Malayalam, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Priya Sharma',phone='9876541007',uname='dr_priya_gyn',
         edu='MBBS, MD - Gynaecology',spec='Gynecologist',exp=12,
         workplace='Fortis La Femme Hospital',addr='154, Bannerghatta Road, Bangalore 560076',
         lat=12.8912,lng=77.5981,about='Women health specialist with expertise in reproductive health.',
         emerg='+91 9876541007',langs='Hindi, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Kavitha Menon',phone='9876541008',uname='dr_kavitha',
         edu='MBBS, DGO, DNB - Obstetrics',spec='Obstetrician',exp=16,
         workplace='Cloudnine Hospital',addr='1533, 16th Cross, Sadashivanagar, Bangalore 560080',
         lat=13.0105,lng=77.5822,about='High-risk pregnancy specialist with 16 years experience.',
         emerg='+91 9876541008',langs='Malayalam, Kannada, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Ravi Prasad',phone='9876541009',uname='dr_ravi_eye',
         edu='MBBS, MS - Ophthalmology',spec='Ophthalmologist',exp=11,
         workplace='Narayana Nethralaya Eye Hospital',addr='121/C, Chord Road, Rajajinagar, Bangalore',
         lat=12.9902,lng=77.5474,about='Retina and cataract surgery specialist.',
         emerg='+91 9876541009',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Meena Iyer',phone='9876541010',uname='dr_meena',
         edu='B.Optom, M.Optom',spec='Optometrist',exp=6,
         workplace='Vision Care Centre',addr='45, MG Road, Bangalore 560001',
         lat=12.9758,lng=77.6095,about='Eye testing and contact lens specialist.',
         emerg='+91 9876541010',langs='Tamil, Kannada, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Suresh ENT',phone='9876541011',uname='dr_suresh_ent',
         edu='MBBS, MS - ENT',spec='ENT Specialist',exp=13,
         workplace='BGS Gleneagles Hospital',addr='Uttarahalli, Bangalore 560060',
         lat=12.8862,lng=77.5340,about='Expert in ear, nose and throat surgeries and treatments.',
         emerg='+91 9876541011',langs='Kannada, English',avail='busy',verified=True),
    dict(cat='Doctor',full_name='Dr. Deepak Dental',phone='9876541012',uname='dr_deepak',
         edu='BDS, MDS - Prosthodontics',spec='Dentist',exp=9,
         workplace='Sabka Dentist Clinic',addr='100 Feet Road, Indiranagar, Bangalore',
         lat=12.9784,lng=77.6408,about='Complete dental care including implants and cosmetic dentistry.',
         emerg='+91 9876541012',langs='Kannada, Hindi, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Ananya Ortho',phone='9876541013',uname='dr_ananya',
         edu='BDS, MDS - Orthodontics',spec='Orthodontist',exp=7,
         workplace='Smiles Forever Dental Clinic',addr='Brigade Road, Bangalore 560025',
         lat=12.9732,lng=77.6088,about='Braces, Invisalign and teeth alignment specialist.',
         emerg='+91 9876541013',langs='English, Kannada',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Pooja Skin',phone='9876541014',uname='dr_pooja',
         edu='MBBS, MD - Dermatology',spec='Dermatologist',exp=10,
         workplace='Kaya Skin Clinic',addr='Forum Mall, Koramangala, Bangalore',
         lat=12.9279,lng=77.6271,about='Skin, hair and nail disorders specialist.',
         emerg='+91 9876541014',langs='Hindi, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Ramesh Endo',phone='9876541015',uname='dr_ramesh_endo',
         edu='MBBS, DM - Endocrinology',spec='Endocrinologist',exp=14,
         workplace='Endocrine Centre Bangalore',addr='Malleshwaram, Bangalore 560003',
         lat=13.0038,lng=77.5613,about='Diabetes, thyroid and hormonal disorder specialist.',
         emerg='+91 9876541015',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Vinod Blood',phone='9876541016',uname='dr_vinod',
         edu='MBBS, DM - Haematology',spec='Hematologist',exp=12,
         workplace='St. John Medical College',addr='Sarjapur Road, Bangalore 560034',
         lat=12.9271,lng=77.6782,about='Blood disorders and bone marrow specialist.',
         emerg='+91 9876541016',langs='Hindi, Kannada, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Shilpa Lung',phone='9876541017',uname='dr_shilpa',
         edu='MBBS, MD - Pulmonology',spec='Pulmonologist',exp=11,
         workplace='Aster CMI Hospital',addr='43/2, NH-7, Hebbal, Bangalore 560092',
         lat=13.0458,lng=77.5970,about='Asthma, COPD and sleep apnoea specialist.',
         emerg='+91 9876541017',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Kiran Gastro',phone='9876541018',uname='dr_kiran',
         edu='MBBS, DM - Gastroenterology',spec='Gastroenterologist',exp=13,
         workplace='Vikram Hospital',addr='71/1, Millers Road, Bangalore 560052',
         lat=12.9905,lng=77.5859,about='Digestive diseases and endoscopy specialist.',
         emerg='+91 9876541018',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Neha Mental',phone='9876541019',uname='dr_neha_psy',
         edu='MBBS, MD - Psychiatry',spec='Psychiatrist',exp=9,
         workplace='NIMHANS Bangalore',addr='Hosur Road, Bangalore 560029',
         lat=12.9402,lng=77.5960,about='Mental health specialist for anxiety, depression and stress.',
         emerg='+91 9876541019',langs='Hindi, English',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Seema Psycho',phone='9876541020',uname='dr_seema',
         edu='M.Phil, Ph.D - Clinical Psychology',spec='Psychologist',exp=8,
         workplace='Mind Space Wellness Centre',addr='Koramangala, Bangalore 560034',
         lat=12.9279,lng=77.6248,about='Cognitive behavioural therapy and counselling specialist.',
         emerg='+91 9876541020',langs='English, Hindi',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Rajiv Cancer',phone='9876541021',uname='dr_rajiv',
         edu='MBBS, MD, DM - Medical Oncology',spec='Oncologist',exp=17,
         workplace='HCG Cancer Centre',addr='#8, Kalinga Rao Road, Bangalore 560027',
         lat=12.9855,lng=77.5950,about='Comprehensive cancer treatment including chemotherapy.',
         emerg='+91 9876541021',langs='Hindi, English, Kannada',avail='available',verified=True),
    dict(cat='Doctor',full_name='Dr. Aisha Emergency',phone='9876541022',uname='dr_aisha',
         edu='MBBS, DNB - Emergency Medicine',spec='Emergency Specialist',exp=10,
         workplace='Victoria Hospital Bangalore',addr='Fort Road, Bangalore 560002',
         lat=12.9716,lng=77.5711,about='24x7 emergency medicine and critical care specialist.',
         emerg='+91 9876541022',langs='Urdu, English, Kannada',avail='available',verified=True),
    # MECHANICS (8)
    dict(cat='Mechanic',full_name='Suresh Kumar',phone='9876542001',uname='suresh_mec',
         edu='ITI Diploma - Automobile Engineering',spec='All Car Brands',exp=12,
         workplace='Suresh Auto Works',addr='56, 4th Cross, Koramangala, Bangalore 560034',
         lat=12.9352,lng=77.6245,about='Expert mechanic for all car and bike brands. 24-hour emergency service available.',
         emerg='+91 9876542001',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Mechanic',full_name='Ravi Mechanic',phone='9876542002',uname='ravi_mec',
         edu='Diploma - Automobile Technology',spec='Tyre & Puncture',exp=8,
         workplace='Ravi Tyre Works',addr='12, Sarjapur Road, Bangalore 560035',
         lat=12.9271,lng=77.6730,about='Fast tyre and puncture repair specialist.',
         emerg='+91 9876542002',langs='Kannada, Tamil',avail='available',verified=False),
    dict(cat='Mechanic',full_name='Ganesh Motors',phone='9876542003',uname='ganesh_mec',
         edu='B.Tech - Mechanical Engineering',spec='Full Car Servicing',exp=15,
         workplace='Ganesh Auto Service Centre',addr='78, Whitefield, Bangalore 560066',
         lat=12.9698,lng=77.7499,about='Complete car servicing center with genuine parts.',
         emerg='+91 9876542003',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Mechanic',full_name='Arjun Battery',phone='9876542004',uname='arjun_mec',
         edu='ITI - Electrical',spec='Battery & Electrical',exp=9,
         workplace='Quick Battery Shop',addr='34, BTM Layout, Bangalore 560076',
         lat=12.9166,lng=77.6101,about='Battery testing, replacement and electrical repairs.',
         emerg='+91 9876542004',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Mechanic',full_name='Cool Car AC',phone='9876542005',uname='coolcar_mec',
         edu='Diploma - AC Technology',spec='Car AC Specialist',exp=7,
         workplace='Cool Car AC Works',addr='90, Indiranagar, Bangalore 560038',
         lat=12.9784,lng=77.6408,about='Car AC repair, gas refill and maintenance specialist.',
         emerg='+91 9876542005',langs='Kannada, English',avail='busy',verified=True),
    dict(cat='Mechanic',full_name='Brake Master',phone='9876542006',uname='brake_mec',
         edu='ITI - Automobile',spec='Brake & Suspension',exp=11,
         workplace='Brake Master Workshop',addr='22, JP Nagar, Bangalore 560078',
         lat=12.9063,lng=77.5857,about='Specialist in brake systems, suspension and steering.',
         emerg='+91 9876542006',langs='Kannada, Tamil',avail='available',verified=True),
    dict(cat='Mechanic',full_name='Dent Pro',phone='9876542007',uname='dent_mec',
         edu='Certificate - Automobile Body Work',spec='Denting & Painting',exp=13,
         workplace='Dent Pro Body Shop',addr='45, Rajajinagar, Bangalore 560010',
         lat=12.9943,lng=77.5519,about='Expert car body denting, painting and restoration.',
         emerg='+91 9876542007',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Mechanic',full_name='Bike Doctor',phone='9876542008',uname='bike_mec',
         edu='ITI - Automobile',spec='Two Wheeler Specialist',exp=10,
         workplace='Bike Doctor Service Centre',addr='67, Malleshwaram, Bangalore 560003',
         lat=13.0038,lng=77.5613,about='All bike and scooter brands servicing and repair.',
         emerg='+91 9876542008',langs='Kannada, English',avail='available',verified=False),
    # TUTORS (8)
    dict(cat='Tutor',full_name='Anita Mathur',phone='9876543001',uname='anita_tut',
         edu='M.Sc Mathematics, B.Ed',spec='Mathematics Tutor',exp=8,
         workplace='Home Tutoring - Indiranagar',addr='12, 4th Cross, Indiranagar, Bangalore 560038',
         lat=12.9784,lng=77.6408,about='IIT-JEE, NEET and board exam mathematics specialist.',
         emerg='',langs='Hindi, English',avail='available',verified=True),
    dict(cat='Tutor',full_name='Prof. Rajan Science',phone='9876543002',uname='rajan_tut',
         edu='M.Sc Physics, M.Ed',spec='Physics, Chemistry, Biology',exp=12,
         workplace='Rajan Tutorial Centre',addr='45, Koramangala, Bangalore 560034',
         lat=12.9279,lng=77.6271,about='Expert science tutor for grades 8-12 and competitive exams.',
         emerg='',langs='Tamil, English',avail='available',verified=True),
    dict(cat='Tutor',full_name='Sheela English',phone='9876543003',uname='sheela_tut',
         edu='MA English Literature, CELTA Certificate',spec='English Communication',exp=6,
         workplace='Speak Well Academy',addr='78, MG Road, Bangalore 560001',
         lat=12.9758,lng=77.6095,about='Spoken English, grammar and IELTS/TOEFL preparation.',
         emerg='',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Tutor',full_name='Kiran Coder',phone='9876543004',uname='kiran_tut',
         edu='B.Tech Computer Science, MCA',spec='Programming & CS',exp=7,
         workplace='Code Academy Bangalore',addr='34, Electronic City, Bangalore 560100',
         lat=12.8391,lng=77.6777,about='Python, Java, Web Development and competitive programming coach.',
         emerg='',langs='Telugu, Kannada, English',avail='available',verified=True),
    dict(cat='Tutor',full_name='Meera Music',phone='9876543005',uname='meera_tut',
         edu='B.Music (Carnatic), Diploma - Guitar',spec='Music Teacher',exp=9,
         workplace='Swar Music Academy',addr='56, Basavanagudi, Bangalore 560004',
         lat=12.9438,lng=77.5765,about='Carnatic classical, guitar, keyboard and vocal training.',
         emerg='',langs='Kannada, Tamil, English',avail='available',verified=True),
    dict(cat='Tutor',full_name='Vijay Artist',phone='9876543006',uname='vijay_tut',
         edu='BFA - Fine Arts, Lalit Kala Academy',spec='Drawing & Painting',exp=10,
         workplace='Vijay Art Studio',addr='23, Rajajinagar, Bangalore 560010',
         lat=12.9943,lng=77.5519,about='Pencil sketching, oil painting and watercolor classes.',
         emerg='',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Tutor',full_name='Deepa Dance',phone='9876543007',uname='deepa_tut',
         edu='Visharad - Bharatanatyam, Diploma - Western Dance',spec='Dance Teacher',exp=11,
         workplace='Deepa Dance Academy',addr='89, Jayanagar, Bangalore 560041',
         lat=12.9255,lng=77.5837,about='Classical Bharatanatyam and western dance forms for all ages.',
         emerg='',langs='Kannada, Tamil, English',avail='available',verified=True),
    dict(cat='Tutor',full_name='CA Ramesh Accounts',phone='9876543008',uname='ramesh_tut',
         edu='CA Final, B.Com',spec='CA and Accounts Coaching',exp=14,
         workplace='CA Ramesh Classes',addr='12, Shivajinagar, Bangalore 560051',
         lat=12.9891,lng=77.5991,about='CA Foundation, Inter and Final level coaching.',
         emerg='',langs='Kannada, Hindi, English',avail='available',verified=True),
    # PLUMBERS (6)
    dict(cat='Plumber',full_name='Ramu Plumber',phone='9876544001',uname='ramu_plu',
         edu='Plumbing Trade Certificate',spec='Pipe Leak & Repair',exp=12,
         workplace='Ramu Plumbing Services',addr='78, HSR Layout, Bangalore 560102',
         lat=12.9116,lng=77.6370,about='All types of plumbing work. 24/7 emergency service.',
         emerg='+91 9876544001',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Plumber',full_name='Drain Expert',phone='9876544002',uname='drain_plu',
         edu='ITI - Plumbing',spec='Drain Cleaning',exp=8,
         workplace='Drain Clean Services',addr='34, Marathahalli, Bangalore 560037',
         lat=12.9592,lng=77.7012,about='Drain unblocking and deep cleaning specialist.',
         emerg='+91 9876544002',langs='Kannada, Telugu',avail='available',verified=False),
    dict(cat='Plumber',full_name='Bath Fitter',phone='9876544003',uname='bath_plu',
         edu='Diploma - Sanitary Works',spec='Bathroom Fitting',exp=10,
         workplace='Bath Master Services',addr='56, Yelahanka, Bangalore 560064',
         lat=13.1005,lng=77.5963,about='Bathroom renovation, tile fixing and fitting specialist.',
         emerg='+91 9876544003',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Plumber',full_name='Toilet Repair Pro',phone='9876544004',uname='toilet_plu',
         edu='ITI - Plumbing',spec='Toilet & Cistern Repair',exp=6,
         workplace='Quick Plumb Services',addr='12, JP Nagar, Bangalore 560078',
         lat=12.9063,lng=77.5857,about='Fast toilet, flush and cistern repair.',
         emerg='+91 9876544004',langs='Kannada, Tamil',avail='available',verified=False),
    dict(cat='Plumber',full_name='Tank Cleaner',phone='9876544005',uname='tank_plu',
         edu='Certificate - Water Tank Maintenance',spec='Water Tank Cleaning',exp=9,
         workplace='Pure Tank Services',addr='45, Whitefield, Bangalore 560066',
         lat=12.9698,lng=77.7499,about='Overhead and underground tank cleaning and disinfection.',
         emerg='+91 9876544005',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Plumber',full_name='Geyser Pro',phone='9876544006',uname='geyser_plu',
         edu='ITI - Plumbing & Electrical',spec='Geyser Installation',exp=11,
         workplace='Water Heater Services',addr='67, Hebbal, Bangalore 560024',
         lat=13.0458,lng=77.5970,about='All brands geyser installation, repair and maintenance.',
         emerg='+91 9876544006',langs='Kannada, Hindi',avail='available',verified=True),
    # ELECTRICIANS (6)
    dict(cat='Electrician',full_name='Kumar Electrician',phone='9876545001',uname='kumar_ele',
         edu='ITI - Electrical, Licensed Electrician',spec='All Electrical Works',exp=9,
         workplace='Kumar Electrical Works',addr='34, BTM Layout, Bangalore 560076',
         lat=12.9166,lng=77.6101,about='Licensed electrician for home, office and commercial wiring.',
         emerg='+91 9876545001',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Electrician',full_name='Wiring Expert',phone='9876545002',uname='wire_ele',
         edu='Diploma - Electrical Engineering',spec='Wiring & Rewiring',exp=12,
         workplace='Safe Wire Electricals',addr='56, Rajajinagar, Bangalore 560010',
         lat=12.9943,lng=77.5519,about='House rewiring, switchboard repair and socket installation.',
         emerg='+91 9876545002',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Electrician',full_name='AC Installer Pro',phone='9876545003',uname='ac_ele',
         edu='Diploma - Refrigeration & AC',spec='AC Installation',exp=8,
         workplace='Cool Air Services',addr='23, Indiranagar, Bangalore 560038',
         lat=12.9784,lng=77.6408,about='All brands split and window AC installation and servicing.',
         emerg='+91 9876545003',langs='Telugu, Kannada',avail='available',verified=True),
    dict(cat='Electrician',full_name='TV Mount Expert',phone='9876545004',uname='tv_ele',
         edu='ITI - Electronics',spec='TV Mounting & Installation',exp=6,
         workplace='Tech Install Services',addr='89, Koramangala, Bangalore 560034',
         lat=12.9279,lng=77.6271,about='LED TV wall mounting, home theatre and speaker installation.',
         emerg='+91 9876545004',langs='Kannada, English',avail='available',verified=False),
    dict(cat='Electrician',full_name='Fuse Master',phone='9876545005',uname='fuse_ele',
         edu='ITI - Electrical',spec='MCB & Fuse Repair',exp=7,
         workplace='Quick Fuse Fix',addr='12, Malleshwaram, Bangalore 560003',
         lat=13.0038,lng=77.5613,about='MCB panel, fuse and circuit breaker repair specialist.',
         emerg='+91 9876545005',langs='Kannada, Tamil',avail='available',verified=True),
    dict(cat='Electrician',full_name='CCTV Pro',phone='9876545006',uname='cctv_ele',
         edu='Diploma - Electronics & Security Systems',spec='CCTV & Security',exp=10,
         workplace='SecureTech Solutions',addr='45, Whitefield, Bangalore 560066',
         lat=12.9698,lng=77.7499,about='CCTV, security alarm and door bell installation.',
         emerg='+91 9876545006',langs='Kannada, English',avail='available',verified=True),
    # CLEANERS (6)
    dict(cat='Cleaner',full_name='Lakshmi Cleaning',phone='9876546001',uname='lakshmi_cln',
         edu='',spec='Home Deep Cleaning',exp=5,
         workplace='Lakshmi Cleaning Services',addr='22, JP Nagar, Bangalore 560078',
         lat=12.9063,lng=77.5857,about='Professional home and office deep cleaning.',
         emerg='+91 9876546001',langs='Kannada, Tamil',avail='available',verified=True),
    dict(cat='Cleaner',full_name='Kitchen Clean Pro',phone='9876546002',uname='kitchen_cln',
         edu='',spec='Kitchen Cleaning',exp=4,
         workplace='Spotless Clean Services',addr='34, HSR Layout, Bangalore 560102',
         lat=12.9116,lng=77.6370,about='Deep kitchen and appliance cleaning specialist.',
         emerg='+91 9876546002',langs='Kannada, Telugu',avail='available',verified=False),
    dict(cat='Cleaner',full_name='Sofa Steam Clean',phone='9876546003',uname='sofa_cln',
         edu='',spec='Sofa & Upholstery',exp=6,
         workplace='Steam Clean Solutions',addr='56, Marathahalli, Bangalore 560037',
         lat=12.9592,lng=77.7012,about='Steam cleaning for sofas, chairs and fabric.',
         emerg='+91 9876546003',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Cleaner',full_name='Bath Shine',phone='9876546004',uname='bath_cln',
         edu='',spec='Bathroom Cleaning',exp=3,
         workplace='Shine Clean Services',addr='12, Jayanagar, Bangalore 560041',
         lat=12.9255,lng=77.5837,about='Complete bathroom sanitization and tile cleaning.',
         emerg='+91 9876546004',langs='Kannada',avail='available',verified=False),
    dict(cat='Cleaner',full_name='Office Sparkle',phone='9876546005',uname='office_cln',
         edu='',spec='Office Cleaning',exp=7,
         workplace='Sparkle Office Clean',addr='78, MG Road, Bangalore 560001',
         lat=12.9758,lng=77.6095,about='Daily and weekly office cleaning contracts available.',
         emerg='+91 9876546005',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Cleaner',full_name='Carpet Fresh',phone='9876546006',uname='carpet_cln',
         edu='',spec='Carpet & Mattress Cleaning',exp=5,
         workplace='Fresh Carpet Services',addr='34, Yelahanka, Bangalore 560064',
         lat=13.1005,lng=77.5963,about='Steam carpet and mattress cleaning service.',
         emerg='+91 9876546006',langs='Kannada, Hindi',avail='available',verified=False),
    # CARPENTERS (5)
    dict(cat='Carpenter',full_name='Master Carpenter',phone='9876547001',uname='master_car',
         edu='Certificate - Furniture Making',spec='All Furniture Work',exp=15,
         workplace='Master Wood Works',addr='56, Rajajinagar, Bangalore 560010',
         lat=12.9943,lng=77.5519,about='Expert in all types of wooden furniture making and repair.',
         emerg='+91 9876547001',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Carpenter',full_name='Door Window Fix',phone='9876547002',uname='door_car',
         edu='ITI - Carpentry',spec='Door & Window Repair',exp=8,
         workplace='Quick Fix Carpentry',addr='23, BTM Layout, Bangalore 560076',
         lat=12.9166,lng=77.6101,about='Door, window, hinge and lock fitting and repair.',
         emerg='+91 9876547002',langs='Kannada, Telugu',avail='available',verified=False),
    dict(cat='Carpenter',full_name='Custom Furniture Pro',phone='9876547003',uname='custom_car',
         edu='Diploma - Interior Design',spec='Custom Furniture Design',exp=12,
         workplace='Design Wood Studio',addr='89, Koramangala, Bangalore 560034',
         lat=12.9279,lng=77.6271,about='Custom-designed furniture for homes and offices.',
         emerg='+91 9876547003',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Carpenter',full_name='Kitchen Modular',phone='9876547004',uname='kitchen_car',
         edu='Diploma - Modular Kitchen Design',spec='Modular Kitchen',exp=10,
         workplace='Kitchen Masters',addr='45, Whitefield, Bangalore 560066',
         lat=12.9698,lng=77.7499,about='Modular kitchen design, installation and fitting.',
         emerg='+91 9876547004',langs='Kannada, Hindi',avail='busy',verified=True),
    dict(cat='Carpenter',full_name='Ceiling Expert',phone='9876547005',uname='ceiling_car',
         edu='Certificate - Interior Works',spec='False Ceiling Installation',exp=9,
         workplace='Ceiling Works Bangalore',addr='12, Hebbal, Bangalore 560024',
         lat=13.0458,lng=77.5970,about='POP, gypsum and grid false ceiling specialist.',
         emerg='+91 9876547005',langs='Kannada, Tamil',avail='available',verified=True),
    # SALON (6)
    dict(cat='Salon',full_name='Ravi Hair Stylist',phone='9876548001',uname='ravi_sal',
         edu='Diploma - Hair Styling, VLCC Certified',spec='Men Haircut & Styling',exp=7,
         workplace='Style Hub Salon',addr='56, Indiranagar, Bangalore 560038',
         lat=12.9784,lng=77.6408,about='Expert men grooming, haircut and beard styling.',
         emerg='',langs='Kannada, Hindi',avail='available',verified=True),
    dict(cat='Salon',full_name='Sunita Beauty',phone='9876548002',uname='sunita_sal',
         edu='Diploma - Beauty Therapy, Enrich Certified',spec='Women Haircut & Styling',exp=9,
         workplace='Sunita Beauty Salon',addr='23, Koramangala, Bangalore 560034',
         lat=12.9279,lng=77.6271,about='Women haircut, blow dry and hair treatment specialist.',
         emerg='',langs='Hindi, Kannada, English',avail='available',verified=True),
    dict(cat='Salon',full_name='Colour Artist',phone='9876548003',uname='colour_sal',
         edu='Certificate - Hair Colouring, L\'Oreal Academy',spec='Hair Colour & Highlights',exp=8,
         workplace='Colour Studio Salon',addr='78, Jayanagar, Bangalore 560041',
         lat=12.9255,lng=77.5837,about='Global hair colouring, highlights and balayage specialist.',
         emerg='',langs='Kannada, English',avail='available',verified=True),
    dict(cat='Salon',full_name='Facial Expert',phone='9876548004',uname='facial_sal',
         edu='Diploma - Skin Care, IICT Certified',spec='Facial & Skin Care',exp=6,
         workplace='Glow Skin Studio',addr='34, Malleshwaram, Bangalore 560003',
         lat=13.0038,lng=77.5613,about='All types of facial, skin brightening and anti-ageing treatments.',
         emerg='',langs='Kannada, Tamil',avail='available',verified=True),
    dict(cat='Salon',full_name='Wax Queen',phone='9876548005',uname='wax_sal',
         edu='Certificate - Beauty & Waxing',spec='Waxing Specialist',exp=5,
         workplace='Smooth Wax Parlour',addr='45, HSR Layout, Bangalore 560102',
         lat=12.9116,lng=77.6370,about='Full body, facial and chocolate waxing specialist.',
         emerg='',langs='Kannada, Telugu',avail='available',verified=False),
    dict(cat='Salon',full_name='Bridal Guru',phone='9876548006',uname='bridal_sal',
         edu='Diploma - Bridal Makeup, MAC Certified',spec='Bridal Makeup',exp=12,
         workplace='Bridal Bliss Studio',addr='89, Basavanagudi, Bangalore 560004',
         lat=12.9438,lng=77.5765,about='Complete bridal makeup, hair styling and pre-bridal packages.',
         emerg='',langs='Kannada, Hindi, English',avail='available',verified=True),
]

created_providers={}
for pd in providers_raw:
    cat=cats.get(pd['cat'].title()) or cats.get(pd['cat'])
    u,_=CustomUser.objects.get_or_create(username=pd['uname'],defaults={
        'first_name':pd['full_name'].split()[0],
        'last_name':' '.join(pd['full_name'].split()[1:]) if len(pd['full_name'].split())>1 else '',
        'email':f"{pd['uname']}@smartservice.com",'role':'provider'})
    prov,_=ServiceProvider.objects.get_or_create(user=u,defaults={
        'category':cat,'full_name':pd['full_name'],'phone':pd['phone'],
        'email':f"{pd['uname']}@smartservice.com",
        'experience_years':pd['exp'],'education':pd['edu'],'specialization':pd['spec'],
        'workplace_name':pd['workplace'],'workplace_address':pd['addr'],
        'workplace_lat':pd['lat'],'workplace_lng':pd['lng'],
        'about':pd['about'],'emergency_contact':pd['emerg'],'languages':pd['langs'],
        'availability':pd['avail'],'verified':pd['verified'],
    })
    created_providers[pd['spec']]=prov
    print(f"  Provider: {pd['full_name']} ({pd['spec']})")

# ── SERVICES ─────────────────────────────────
svcs=[
    ('Doctor','General Physician',500,30,'General health consultation and diagnosis for common illnesses.','General Physician'),
    ('Doctor','Cardiologist',1200,45,'Heart specialist for cardiac conditions, ECG, and heart health.','Cardiologist'),
    ('Doctor','Neurologist',1200,45,'Brain and nerve specialist for headaches, seizures and disorders.','Neurologist'),
    ('Doctor','Orthopedic Doctor',900,45,'Bone, joint and muscle specialist for fractures and pain.','Orthopedic Doctor'),
    ('Doctor','Physiotherapist',600,60,'Physical therapy for injury recovery and mobility improvement.','Physiotherapist'),
    ('Doctor','Pediatrician',600,30,'Child specialist for infants, children and teenagers.','Pediatrician'),
    ('Doctor','Gynecologist',800,45,'Women health specialist for reproductive and hormonal health.','Gynecologist'),
    ('Doctor','Obstetrician',900,45,'Pregnancy specialist for prenatal care and delivery.','Obstetrician'),
    ('Doctor','Ophthalmologist',700,30,'Eye specialist for vision problems and infections.','Ophthalmologist'),
    ('Doctor','Optometrist',400,30,'Eye testing and prescription glasses and contact lenses.','Optometrist'),
    ('Doctor','ENT Specialist',700,30,'Ear, nose and throat specialist.','ENT Specialist'),
    ('Doctor','Dentist',500,45,'Dental checkup, cleaning, filling and tooth extraction.','Dentist'),
    ('Doctor','Orthodontist',1000,45,'Braces, aligners and teeth straightening specialist.','Orthodontist'),
    ('Doctor','Dermatologist',700,30,'Skin, hair and nail specialist for all skin conditions.','Dermatologist'),
    ('Doctor','Endocrinologist',900,45,'Diabetes, thyroid and hormone specialist.','Endocrinologist'),
    ('Doctor','Hematologist',1000,45,'Blood disorder specialist for anemia and clotting issues.','Hematologist'),
    ('Doctor','Pulmonologist',900,45,'Lung and breathing specialist for asthma and respiratory diseases.','Pulmonologist'),
    ('Doctor','Gastroenterologist',1000,45,'Stomach, liver and digestive system specialist.','Gastroenterologist'),
    ('Doctor','Psychiatrist',1200,60,'Mental health doctor for anxiety, depression and psychiatric care.','Psychiatrist'),
    ('Doctor','Psychologist',800,60,'Counseling and therapy for mental and emotional health.','Psychologist'),
    ('Doctor','Oncologist',2000,60,'Cancer specialist for diagnosis, treatment and chemotherapy.','Oncologist'),
    ('Doctor','Emergency Specialist',1500,30,'Emergency care for critical and life-threatening conditions.','Emergency Specialist'),
    ('Mechanic','Oil Change',350,45,'Engine oil and filter replacement for all vehicles.','All Car Brands'),
    ('Mechanic','Tyre Puncture Repair',150,30,'Fast puncture repair for all tyre types.','Tyre & Puncture'),
    ('Mechanic','Full Car Service',1500,180,'Complete car servicing with all fluid checks.','Full Car Servicing'),
    ('Mechanic','Battery Replacement',800,30,'Car battery testing and replacement.','Battery & Electrical'),
    ('Mechanic','AC Repair',1200,120,'Car air conditioning repair and gas refill.','Car AC Specialist'),
    ('Mechanic','Brake Service',900,90,'Brake pad and disc inspection and replacement.','Brake & Suspension'),
    ('Mechanic','Denting and Painting',2500,240,'Car body dent repair and painting.','Denting & Painting'),
    ('Mechanic','Two Wheeler Service',500,60,'Motorbike and scooter full servicing.','Two Wheeler Specialist'),
    ('Tutor','Mathematics',400,60,'One-on-one math coaching for grades 6 to 12.','Mathematics Tutor'),
    ('Tutor','Science Coaching',450,60,'Physics, Chemistry and Biology coaching.','Physics, Chemistry, Biology'),
    ('Tutor','English Speaking',350,60,'Spoken English and grammar improvement.','English Communication'),
    ('Tutor','Computer Science',500,60,'Programming and CS fundamentals.','Programming & CS'),
    ('Tutor','Music Lessons',400,60,'Guitar, piano and vocal music lessons.','Music Teacher'),
    ('Tutor','Drawing and Art',350,60,'Sketching and painting coaching.','Drawing & Painting'),
    ('Tutor','Dance Classes',400,60,'Classical and western dance coaching.','Dance Teacher'),
    ('Tutor','CA and Accounts',600,60,'Commerce and CA foundation coaching.','CA and Accounts Coaching'),
    ('Plumber','Pipe Leak Repair',250,60,'Fix leaking pipes, taps and joints.','Pipe Leak & Repair'),
    ('Plumber','Drain Cleaning',300,45,'Unblock and clean clogged drains.','Drain Cleaning'),
    ('Plumber','Bathroom Fitting',800,120,'Install showers, taps and bathroom fittings.','Bathroom Fitting'),
    ('Plumber','Toilet Repair',350,45,'Fix flush, cistern and toilet seat issues.','Toilet & Cistern Repair'),
    ('Plumber','Water Tank Cleaning',600,90,'Overhead water tank cleaning.','Water Tank Cleaning'),
    ('Plumber','Geyser Installation',700,90,'Water heater installation and repair.','Geyser Installation'),
    ('Electrician','Fan Installation',300,60,'Install ceiling or wall fans safely.','All Electrical Works'),
    ('Electrician','Wiring Repair',500,90,'Fix faulty wiring, sockets and switches.','Wiring & Rewiring'),
    ('Electrician','AC Installation',1000,120,'Split AC installation and fitting.','AC Installation'),
    ('Electrician','TV Mounting',400,60,'Wall mount LED/LCD TV.','TV Mounting & Installation'),
    ('Electrician','MCB Fuse Repair',200,30,'Replace blown fuses and faulty MCBs.','MCB & Fuse Repair'),
    ('Electrician','CCTV Installation',1500,120,'Security camera installation and setup.','CCTV & Security'),
    ('Cleaner','Home Deep Clean',1200,240,'Full deep cleaning of your home.','Home Deep Cleaning'),
    ('Cleaner','Kitchen Cleaning',600,90,'Complete kitchen and appliance cleaning.','Kitchen Cleaning'),
    ('Cleaner','Sofa Cleaning',500,60,'Professional sofa and upholstery cleaning.','Sofa & Upholstery'),
    ('Cleaner','Bathroom Cleaning',400,60,'Deep bathroom sanitization and cleaning.','Bathroom Cleaning'),
    ('Cleaner','Office Cleaning',1500,180,'Professional office workspace cleaning.','Office Cleaning'),
    ('Cleaner','Carpet Cleaning',700,90,'Steam cleaning for carpets and mattresses.','Carpet & Mattress Cleaning'),
    ('Carpenter','Furniture Repair',400,90,'Fix broken chairs, tables and cupboards.','All Furniture Work'),
    ('Carpenter','Door Window Repair',350,60,'Fix doors, windows, hinges and locks.','Door & Window Repair'),
    ('Carpenter','Custom Furniture',3000,480,'Design and build custom furniture.','Custom Furniture Design'),
    ('Carpenter','Modular Kitchen',5000,480,'Modular kitchen cabinets and fitting.','Modular Kitchen'),
    ('Carpenter','False Ceiling',4000,360,'POP or gypsum false ceiling installation.','False Ceiling Installation'),
    ('Salon','Haircut Men',150,30,'Professional haircut, wash and style for men.','Men Haircut & Styling'),
    ('Salon','Haircut Women',300,45,'Women haircut, trim and blowdry.','Women Haircut & Styling'),
    ('Salon','Hair Colour',800,90,'Global hair colour, highlights and toning.','Hair Colour & Highlights'),
    ('Salon','Facial',500,60,'Skin cleansing, scrubbing and facial massage.','Facial & Skin Care'),
    ('Salon','Waxing',300,45,'Full or partial waxing service.','Waxing Specialist'),
    ('Salon','Bridal Makeup',5000,120,'Full bridal makeup and hair styling.','Bridal Makeup'),
]
for cat_name,name,price,dur,desc,spec in svcs:
    prov=created_providers.get(spec)
    obj,cr=Service.objects.get_or_create(name=name,defaults={
        'category':cats[cat_name],'price':price,'duration_minutes':dur,
        'description':desc,'specialization':spec,'available':True,'provider':prov})
    if not cr and prov: obj.provider=prov; obj.save()
print(f"  Services: {Service.objects.count()}")

# ── USERS ─────────────────────────────────────
admin,c=CustomUser.objects.get_or_create(username='admin',defaults={
    'email':'admin@smartservice.com','first_name':'Admin','last_name':'User',
    'role':'admin','is_staff':True,'is_superuser':True})
if c: admin.set_password('admin123'); admin.save(); print("  Admin: admin/admin123")

sagar,c=CustomUser.objects.get_or_create(username='sagar',defaults={
    'email':'sagar@example.com','first_name':'Sagar','last_name':'P',
    'phone':'9972889659','role':'user'})
if c: sagar.set_password('sagar123'); sagar.save(); print("  User: sagar/sagar123")

print(f"\nDone!")
print(f"  Categories : {Category.objects.count()}")
print(f"  Services   : {Service.objects.count()}")
print(f"  Providers  : {ServiceProvider.objects.count()}")
print(f"  Users      : {CustomUser.objects.count()}")
print(f"\n  Admin : admin / admin123")
print(f"  User  : sagar / sagar123")
print(f"  URL   : http://127.0.0.1:8000")
